### ISSUE TITLE
CSS Reset

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#124]
CSS Reset for Aurelia UX to enable consistent rendering across browsers.

**Comment by ZHollingshead** [comment]
@EisenbergEffect I am going to pick this one up, it should be quick. Is there a particular CSS reset we have our eye on using or are we going to roll our own?

**Comment by EisenbergEffect** [comment]
I dropped one in the showcase app that worked well. Can we pull it out of there and embed it into the ux core?

**Comment by ZHollingshead** [comment]
Yep, sure thing.

**Comment by ben-girardet** [comment]
Good idea.

Just dropping some infos here as it might be useful / interesting. I've made some tests using a combination of Aurelia UX and Bootstrap 4. I'm currently doing this with the use of a custom plugin that parse bootstrap SCSS (with a set of custom SCSS variables for the project) and merge the bootstrap config variables into Aurelia UX JS variables (with an Aurelia CLI custom task). Basically the primary bootstrap color is parsed from the SCSS and imported as JS variable into AureliaUX instance (secondary becomes accent, and the light and dark values are computed using lighten and darken mixins from bootstrap). With this system I can pick and choose what part of bootstrap / aurelia UX I use in my projects. For exemple, I use lots of cards and list-group + the grid from bootstrap and nearly everything from aurelia ux (inputs, buttons, icons, ...).

Why dropping this here ? Because I was wondering if adding the CSS reset in the Core of Aurelia UX could cause any incompatibilities with Bootstrap 4 and if yes, how to avoid this ?

**Comment by EisenbergEffect** [comment]
I think there should be a method on the UX config object that applies the reset. It should be called as part of the default configuration, but for advanced scenarios like merging with bootstrap, it should be possible to do a manual config and not apply the reset.
