### ISSUE TITLE
Icon component is not part of components package

### ISSUE THREAD

**Issue by dudluk** [aurelia/ux#128]
**I'm submitting a bug report**

* **Library Version:**
0.6.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack-3.8.1

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**
The ux-icon component is not part of @aurelia-ux/components package

**Expected/desired behavior:**

* **What is the expected behavior?**
The ux-icon component is a part of @aurelia-ux/components package 

* **What is the motivation / use case for changing the behavior?**
All other components are part of that package

**Comment by ZHollingshead** [comment]
For now this is intentional. The reason behind this is the UX Icon component is very large and does not benefit from tree shaking due to the way the Icons are currently included. The Icon map is the source of the bloat at over 300kb which is larger than the rest of the library.

. | Core + Components  | Core + Components (Minified) | Core + Components + Icons | Core + Components + Icons  (Minified)
---|---|---|---|----
**Parsed**                    | 219.62 kb | 103.17 kb | 571.13 kb | 376.6 kb
**GZipped**                 | 27.33 kb | 17.19 kb | 99.84 kb | 88.4 kb

Visual of a production build with tree shaking and minification
![image](https://user-images.githubusercontent.com/22172935/34233084-f8bc6874-e5a8-11e7-86fe-ff06fec34ea6.png)

**Comment by dudluk** [comment]
It makes sense, I think we can close this issue then :)
