### ISSUE TITLE
ux-slider

### ISSUE THREAD

**Issue by shannonhorn** [aurelia/ux#20]
Implement the ux-slider component for Material and iOS design.

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #14](https://github.com/aurelia/ux-components/issues/14) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rdelhommer** [comment]
I'd be interested in working on this component if it's not something that's been already unofficially worked on a bit.  I took a look at the material-ui slider implementation at doesnt seem like anything that's outside the realm of my abilities.  I havent made any contributions to aurelia yet, but I've used it for the last year at work and really enjoy it. Would especially like to get involved with this ux project.

**Comment by bigopon** [comment]
@rdelhommer that'd be awesome 👍

**Comment by rdelhommer** [comment]
Sounds great!  I'll play around a little bit with the project just to get things going and let you know if I run into any issues.

From a first glace, it looks like I should be creating a new mono repo for the slider using the boilerplate as a jumping off point.

**Comment by rdelhommer** [comment]
So I made fairly basic implementation [here](https://github.com/rdelhommer/ux/tree/master/packages/slider) based off of the material-ui react [slider](https://github.com/mui-org/material-ui/tree/56fcebb045e3a0f675dc0ddc665a6c5f300dde99/packages/material-ui-lab/src/Slider).  I didn't want to go to far without getting some feedback on what I've done since I don't have the most formal experience developing UI components.

A couple of specific questions that I have going forward is:
* Are there any particular things I should be theming or you'd like to be themed? Currently, I have background-color and the thumb diameter
* Are there any specific bindable options that you guys would like to have?  Currently, I have min and max
* Anything I should be doing for accessibility and screen readers?
* Do you have any recommendations for testing my component other than in the GistRun playground?

**Comment by bigopon** [comment]
mostly theming will be based on pattern that we have with existing components.
About bindable options, generally we try to make the control as close to native control as possible, you can see that reflects in `ux-select` APIs
accessibility should be done as much as implementer can, we can always improve later, so it's not a big deal for now if you don't feel comfortable.
There is testing infra in place, but if you have issue with running it, maybe i can help. even with some preliminary tests explaining what integration tests should there be are already good.

Overall, the quality is the target, but we need more champions beside @serifine to drive this forward. I can help too if there is main driver. Thanks for this @rdelhommer

**Comment by rdelhommer** [comment]
Sure that all sounds good.  I wouldn't consider myself a champion, but I'm certainly interested in continuing to work on this repo with @serifine.  It would be nice to have a community-built ui library that I can use in my side projects.  Plus I'm hoping it can be a good learning experience for me for UI development best practices.

For now, I'll leave the aria/screen-reader accesibilty stuff for later since I'm not really sure what to do for that and just focus on getting the control as close to native as possible and also finishing up some of the fancier styles like hover and focus.

Regarding the testing infra.  None of the other components had unit tests so I just left it the same as all the others for now.  I can also add some tests though before I submit for official review.

**Comment by rdelhommer** [comment]
had to take a little bit of a break but I think I'm pretty close to being finished.  Can you point me to an example that shows how to implement ios styles?  I dont really see anything that stands out in the component css files.  Once I do the ios styles it should be ready to go and I'll make the PR

**Comment by EisenbergEffect** [comment]
@rdelhommer We haven't gotten around to doing iOS styles yet. So, if you don't need them yourself, we could just take the PR with material styles only. @serifine can comment more on our plan for how we were going to handle iOS though.

**Comment by serifine** [comment]
I agree, make the PR with just the Material styles unless you need them yourself. We really need someone innately familiar with the control styles that can champion the styling of the iOS version of the components.

**Comment by EisenbergEffect** [comment]
This might be a nice opportunity for @scriswell to get involved again. He know platform control styles like the back of his hand. He's been working with Aurelia in his day job...so maybe we could give him a walk-through of this library, get him set up, and then let him go to town on the CSS? I bet he could get a lot done with a little bit of occasional guidance from you @serifine, if you two are both up for it.

**Comment by scriswell** [comment]
I'm up for it for sure!

**Comment by bigopon** [comment]
Added by @serifine and enhanced by @ben-girardet . Closing this
