### ISSUE TITLE
ux-radio

### ISSUE THREAD

**Issue by Vheissu** [aurelia/ux#21]
Implement the ux-radio component for Material and iOS design.

**Comment by Vheissu** [comment]
I'll take this one @EisenbergEffect if you can assign it to me.

**Comment by groundzero2010** [comment]
I'd like to help out with this.

**Comment by ZHollingshead** [comment]
Go for it!

**Comment by jdanyow** [comment]
some ideas in this gist: https://gist.run/?id=a78d15898660218b8438e34dcc31f390

**Comment by ZHollingshead** [comment]
So perhaps two components, one for a simple use case, one for a more complex one.

Single Radio component for simple use cases
``` html
<ux-radio value="male" checked.bind="gender">Male</ux-radio>
```
@jdanyow multi input idea that could wrap up the original.
``` html
<ux-radio-group items-source.bind="colors" value.bind="color1"></ux-radio-group>
```
Thoughts?

**Comment by ZHollingshead** [comment]
I will leave this here as well, from an earlier discussion on gitter.

To expand on what I copied below, the `ux-checkbox` currently will have the same bindings for the value and checked.bind, so perhaps we could have a single wrapper for both components since the binding and styles will be close if not the same.

------------

So the standard use of a radio button is:
``` html
  <input type="radio" name="color" value="red"> Red
  <input type="radio" name="color" value="blue"> Blue
```
I think there is a good game plan going forward with the following attributes:
value: represents the value of the radio button, follows the standard html usage of value in a checkbox
checked: represents the property on the view model to bind to, follows how Aurelia binds to radios in the docs
label(optional): represents an optional label that can also be provided in the slot

Leaving the following usage
``` html
  <ux-radio value="red" checked.bind="color"></ux-radio>
  <ux-radio value="blue" checked.bind="color"></ux-radio>

  <ux-radio value="red" checked.bind="color">Red</ux-radio>
  <ux-radio value="blue" checked.bind="color">Blue</ux-radio>

  <ux-radio value="red" checked.bind="color" label="Red"></ux-radio>
  <ux-radio value="blue" checked.bind="color" label="Blue"></ux-radio>
```

**Comment by jdanyow** [comment]
@ZHollingshead re: https://github.com/aurelia/ux/issues/21#issuecomment-293614445

 two components: the radio primitive and the radio group/selector- sounds good :+1:

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #13](https://github.com/aurelia/ux-components/issues/13) via [**ZenHub**](https://www.zenhub.com/)
