### ISSUE TITLE
[suggestion] Typestyle alternative to manage variables on css

### ISSUE THREAD

**Issue by AbraaoAlves** [aurelia/ux#24]
**I'm submitting a feature request**
Typestyle support

* **What is the expected behavior?**
Share variables with type safe

* **What is the motivation / use case for changing the behavior?**
Safe, ease manage and easy refactory. [And much more ... ](http://typestyle.io/#/why)

**Comment by moodledan** [comment]
@AbraaoAlves have you seen this lib [postcss](http://postcss.org) and [cssnext](http://cssnext.io/)? 

Also this very useful blog post with details on how to make use of the above within an Aurelia app: [Using tomorrow’s CSS with Aurelia (typescript) and PostCSS](https://www.eriklieben.com/using-tomorrows-css-with-aurelia-typescript-and-postcss/)

I guess I'm waiting on some docs around implementation of CSS processors so that I can better organise my CSS and associated variables in a much better way than the current examples in this repo.

**Comment by EisenbergEffect** [comment]
You can use whatever you want in your own apps. The component library itself needs special capabilities internally.
