### ISSUE TITLE
Theme property input binding not working as css var

### ISSUE THREAD

**Issue by stephenlautier** [aurelia/ux#32]
**I'm submitting a bug report**

* **Library Version:**
0.1.14

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
Chrome 55

* **Language:**
TypeScript 2.1

**Current behavior:**
Passing a `foreground` color to the `ux-button` such as `blue` (assuming it takes valid CSS colors, I also tried hex) is not working. Example:
```html
<ux-button foreground="blue">Button</ux-button>
```
Color is not being changed.

**Expected/desired behavior:**
I expect that the color changes according to the provided attribute color, since its as following 
`color: ${foreground || $design.accentForeground};`

I also noticed that there are no examples of these being passed, is it not implemented yet?
I'm testing on the ux-showcase and it also happens there.

**Comment by verbedr** [comment]
I don't think that it works like you are expecting it to work. The css is a requirement but the values are defaulted to the current style or will fall-back to a design setting. The 'foreground' property is not binded to the control and the button control has no way to set a specific colour .

Anyway this doesn't mean that we should not have this functionality of course. But since I to just recently got interested in this project, I can't say anything about the how or the what of some elements. Currently only @EisenbergEffect can tell what we could expect with this button (he is the only one working on #15). As far as I have scanned the material design documentation we should remain within the range of the pallet and fab buttons should be defaulted to the accent colour otherwise use the foreground color. But I see exceptions in the md doc (mainly use of 'red' color)

btw please correct my I'm wrong.

**Comment by stephenlautier** [comment]
@verbedr not entirely sure either, however other properties such as `type` within [ux-button-theme](https://github.com/aurelia/ux/blob/master/src/button/ux-button-theme.ts#L5) thats how its used (as in thats how its [passed as an input](https://github.com/aurelia/app-ux-showcase/blob/master/src/components/buttons.html#L17)), and a property which is named `foreground` i assumed its use the same way :)

**Comment by moodledan** [comment]
I'm not sure why but based on the template the 'foreground' property isn't used in the way the `type` property is. 

Theres no binding set in the [ux-button](https://github.com/aurelia/ux/blob/master/src/button/ux-button.ts) component either so adding a `ux-button` with a foreground attribute won't do anything as far as I can tell.

However there must be a reason why `public foreground: string;` is specified, its referenced in [ux-button-theme.css](https://github.com/aurelia/ux/blob/master/src/button/ux-button-theme.css#L41).

**Comment by verbedr** [comment]
@stephenlautier I think I found it. You need to bind against the theme property and either provide a theme name or object ... something like this

<ux-button theme.bind="{ foreground: 'blue' }"></ux-button>

**Comment by moodledan** [comment]
@verbedr nice!

**Comment by verbedr** [comment]
@moodledan yes I saw that and traced it back to its usage. Still need to work out what exactly would happen when you specify a theme name. I guess you can add the inline theme objects as a resource and reference them. But this is an educated guess ...

**Comment by stephenlautier** [comment]
@verbedr cool thanks! i've tested that and it works :). 

What i found confusing is they are both defined in the same way but the usage is different, I dont know how they are handled differently.

**Comment by verbedr** [comment]
@stephenlautier 
I guess you are partly right, it is part of the UX design and is achieved by convention and by decorators.

- theme is bindable because at ux-button.ts its decorated like that.
`@bindable public theme = null;`
- By convention every component has a ...-theme component (ux-button and ux-button-theme)
- And this is all wired up by a style-factory making sure that the correct values end up were they should. 

As a side note ... when I was looking at the ux-button component code, I also saw that they check the theme element for size, type and effect.  Thus making it possible to write something like this
`<ux-button theme.bind="{ type: 'flat' }"></ux-button>`
which would be exactly the same as
`<ux-button type="flat"></ux-button>`
This makes sense when you realize that the theme does not need to be an inline object but can be any viewResource added by the parent element (using a require statement).

**Comment by stephenlautier** [comment]
@verbedr thanks for the explanation  👍
