### ISSUE TITLE
form layout & labels

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#40]
Implement the form layout & labels components for Material and iOS design.

**Comment by ZHollingshead** [comment]
@EisenbergEffect I can tackle this one next.

Just looking here is what I have identified so far:
* Form control groups
* Labels to pair with controls
* A quick way for a form to reset all inputs
* A submit event for the form

Here are the pieces I have identified.
`ux-form` for groups
`ux-form-group` for grouping together labels and input components.
Questions I have are:
* Should this include any kind of layout. For example, a row of controls or control groups?




And of course, is there anything that was intended to be in this control that I missed or got wrong?

**Comment by EisenbergEffect** [comment]
Excellent. I would like to be able to handle basic layout such as label positioning as appropriate for Material vs. iOS design languages.

**Comment by EisenbergEffect** [comment]
@ZHollingshead Can you email me? You can find my email in my GitHub profile. Thanks!

**Comment by ZHollingshead** [comment]
@EisenbergEffect Sure. I do not see your email on your profile, just your website. I have mine on my profile as well.

**Comment by EisenbergEffect** [comment]
Ah funny. Sorry. You can use the one from the site.


On March 17, 2017 at 11:21:58 AM, Zacharey Hollingshead (
notifications@github.com) wrote:

@EisenbergEffect <https://github.com/EisenbergEffect> Sure. I do not see
your email on your profile, just your website. I have mine on my profile as
well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aurelia/ux/issues/40#issuecomment-287433618>, or mute
the thread

**Comment by ZHollingshead** [comment]
@EisenbergEffect Not there either. Here is mine. zach.hollingshead@gmail.com

**Comment by EisenbergEffect** [comment]
Ok, cool. Thanks :)

**Comment by ZHollingshead** [comment]
If you were going to be using a form component, what features would you expect/desire it to have? For example, would you want a form made for Aurelia to post to a method on the view model?

**Comment by khuongduybui** [comment]
Maybe look at this for some inspiration: https://aurelia-form.spoonx.org/
