### ISSUE TITLE
Icon Handling

### ISSUE THREAD

**Issue by serifine** [aurelia/ux#54]
- [ ] ux-icon component

- [ ] SVG Based Icons

- [ ] Material Design Icon Set

- [ ] IOS Icon Set

- [ ] Build process to manage multiple icon sets and build the icon-map.ts file

**Comment by ZHollingshead** [comment]
Through discussions so far this should use the following:
- Different icon sets for Material and iOS
- Use SVG based icons

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #10](https://github.com/aurelia/ux-components/issues/10) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ZHollingshead** [comment]
I think we need to take another look at Icons soon all around. There are two points.

1. The current way this is done, through an icon map, prevents certain aspects such as letting Webpack's tree shaking decrease the file size, mostly due to the fact that the icon set is converted to a large JSON file instead of using the native SVG files.

2. Soon we will need to add support for IOS Icons, and I feel however this is accomplished needs to be done in such a way that it is easily extensible so that custom icon sets can be added or removed.

**Comment by bigopon** [comment]
We have settled with ability to configure icon set from user app, with a default icon set provided, for now. Can have a look here. Close this ticket for now. If we need to iterate on this again, let's open a new ticket.
