### ISSUE TITLE
Office Design Language

### ISSUE THREAD

**Issue by LarsKemmann** [aurelia/ux#57]
**I'm submitting a feature request**

* **Language:**
TypeScript 2.2

**Expected/desired behavior:**
I'd like to see Office Design Language supported. I've seen "Microsoft" and "Windows" references elsewhere in this project. I think the Office Design Language is slightly distinct from those, being more specific to certain types of applications. It also has a very active set of projects including [one for just the core styling, grid, etc](https://github.com/OfficeDev/office-ui-fabric-core/).

I'm looking for some (probably more than some :)) guidance on how to go about this. Where do I start? What should my first steps be, since I don't think anything exists for this yet in Aurelia UX? Can you give me some kind of "Roadmap to Hello World"-type guidance (list of tasks, types of work needed, etc.)? I want to be sure not to bite off too much -- a walking skeleton with the right fonts would be a good first milestone, and then maybe I can add in a button as a milestone after that?

* **What is the motivation / use case for changing the behavior?**
I'm developing an application wherein I'd like to combine the Office Design Language and Aurelia.

**Comment by EisenbergEffect** [comment]
At Microsoft I've connected with the Microsoft Web Framework team and shown them Aurelia and started talking about possibilities. The MWF team makes a set of components that match Microsoft's official design language and syncs with updates in design, such as Project Neon.

I haven't connected the the Office Fabric team yet. I'll try to find the right person to talk to about that.

If you would like to help build something like this into Aurelia UX, we would certainly welcome the contribution. The place to start would be exploring some of our core primitives such as colors, designs and platforms. After that, take a look at how a few of our existing components are put together so you get the feel. Currently, we only have one design language in UX: Material Design. We'll be adding iOS next. As part of that we'll be adding some more infrastructure that allows loading different CSS and different HTML based on the design language. Once that's in place, you would take one of our existing components and determine if you can use the same HTML. If so, then you would look at the CSS and determine if you can use that by simply changing variables or if you need a new CSS file. Based on those choices, you would do one or the other and then you would be done :)

**Comment by LarsKemmann** [comment]
Thanks @EisenbergEffect! It sounds like I need to wait for that infrastructure to be in place before I can really contribute. That'll actually give me a chance to work with the Office Fabric and/or MWF components for now and just figure out how to data-bind them with Aurelia. That's probably enough of a challenge for right now.

**Comment by Alexander-Taran** [comment]
Stale for almost a year
but promising

**Comment by LarsKemmann** [comment]
@Alexander-Taran I've tried to get Aurelia working with the Office UI Fabric React components (since I figured biting off an actual Aurelia UX-native rebuild of the components was taking on too much). Unfortunately that's hitting some roadblocks (https://discourse.aurelia.io/t/react-integration/544/17).

I would _love_ to see Aurelia UX support the Microsoft (Windows and/or Office) design language.

**Comment by LarsKemmann** [comment]
@EisenbergEffect If I have understood correctly, the Microsoft Web Framework is only intended to be used for Microsoft's own products and brand; it's not being published as a design standard. I've seen some similar not-for-general-use clauses in the terms around Office UI Fabric. Do the people you've talked to see that differently, or do they really not want people to be able to use their UI conventions the way that Apple and Google, for example, have been promoting their design languages?

**Comment by fkleuver** [comment]
@LarsKemmann I attempted building an Aurelia app with Office UI Fabric 2 years ago but ended up going with a hand-rolled style. It does seem to be intended for use with Office products. To quote the front page:

> The official front-end framework for building experiences that fit seamlessly into Office and Office 365

To be fair, I'm not sure if you'd even *want* to have an arbitrary app look like it's an Office product. Neat as it can look, you give up your own brand identity.

That doesn't mean there's no place for Office UI Fabric in Aurelia UX. Having worked at a large Microsoft partner that built custom solutions on top of SharePoint and the likes, I've seen a fairly large demand in businesses to "drag and drop" their own internal LOB UI's together. For example, managers at customer service departments love having the ability to create wizards that capture domain knowledge, so they can hire cheaper people who just click through them based on answers they get. They do this at Microsoft too.

Use cases like that is where Aurelia UX would really shine if it had a more desktop-oriented design option as opposed to the mobile-oriented Material Design. For example I could see it being integrated into SharePoint Web Parts and you could drag-and-drop pages/forms/wizards together in no-time.

There's also a huge market in add-ons and customizations for Dynamics CRM and Power BI, which are all connected to the Office 365 cloud. There are many service providers for whom making those customizations is their core business (I have also done this on occasion), and Aurelia UX components with Office UI Fabric could save huge amounts of time there.

Conclusion: whether or not MWF and Office UI Fabric are intended to be used with Microsoft products exclusively, isn't really relevant for the question whether it can be useful or not.
That said, it does make a difference in how it's "promoted" with Aurelia UX because it narrows down (or perhaps opens up?) the target audience to Microsoft B2B.

**Comment by EisenbergEffect** [comment]
Things have changed inside Microsoft, last time I talked to the contacts I had. MWF was changing and there was new work on https://fluentweb.com/ However, the future of both of these projects seems uncertain. As is typical at Microsoft, employees that are lower on the chain want to do these things but people higher in the chain frequently don't want to invest. It's hard to say what will happen.

**Comment by LarsKemmann** [comment]
@EisenbergEffect Thanks for your insight. I hope we'll get some more clarity around Build.

**Comment by LarsKemmann** [comment]
@EisenbergEffect This sounds _really_ promising...
https://github.com/OfficeDev/office-ui-fabric-core/issues/852#issuecomment-380170300

Note that it would have to be just the Core pieces (styling etc.) that we pull into Aurelia UX, because the React components aren't compatible (once you start to do any kind of nesting) as we recently discovered. But that should be fine since we want to reuse the control behaviors that are defined in this project, I would think.
